# Basic
APP_TITLE = "NAI NAI"
BG_COLOR = "#343541"
TEXT_COLOR = "#ffffff"
FONT = "Helvetica 12"
BORDER_COLOR = "#484954"

# Exchanging words
YOUR_NAME = "User"
YOUR_TEXT_COLOR = "#ffffff"
CHAT_NAME = "SzopGPT"
CHAT_TEXT_COLOR = "#FF5733"
DIALOGUE_FONT = "Helvetica 13 bold"
BONUS_FUNCTION_COLOR = "#ffd1dc"

# User Input Box
USER_INPUT_FONT = "Helvetica 20 bold"

# Sidebar
SIDEBAR_BUTTON_COLOR = "#1f2027"
SIDEBAR_COLOR = "#24252e"
CHOOSEN_BUTTON_COLOR = "#343541"